(defconstant +upper-left+ 0 )
(defconstant +upper-middle+ 1 )
(defconstant +upper-right+ 2 )
(defconstant +middle-left+ 3 )
(defconstant +middle-central+ 4 )
(defconstant +middle-right+ 5 )
(defconstant +lower-left+ 6 )
(defconstant +lower-middle+ 7 )
(defconstant +lower-right+ 8 )

(defvar *position* (list +upper-left+ +upper-middle+ +upper-right+ +middle-left+ +middle-central+ +middle-right+ +lower-left+ +lower-middle+ +lower-right+))

(print *position*)

(defconstant +part-none+ 95 )
(defconstant +part-arm-left+ 97 )
(defconstant +part-arm-right+ 65 )
(defconstant +part-boobs+ 98 )
(defconstant +part-clavicle+ 99 )
(defconstant +part-ear-left+ 101 )
(defconstant +part-ear-right+ 69 )
(defconstant +part-eye-left+ 121 )
(defconstant +part-eye-right+ 89 )
(defconstant +part-hair-top+ 111 )
(defconstant +part-hair-left+ 114 )
(defconstant +part-hair-right+ 82 )
(defconstant +part-hand-left+ 100 )
(defconstant +part-hand-right+ 68 )
(defconstant +part-mouth+ 109 )
(defconstant +part-tail+ 116 )
(defconstant +part-bell+ 108 )
(defconstant +part-exclamation-mark+ 120 )
(defconstant +part-exclamation-marks+ 88 )
(defconstant +part-heart+ 104 )
(defconstant +part-hearts+ 72 )
(defconstant +part-lantern+ 110 )
(defconstant +part-question-mark+ 113 )
(defconstant +part-question-marks+ 81 )
(defconstant +part-wool-ball+ 119 )

(defvar *part* (list +part-none+ +part-arm-left+ +part-arm-right+ +part-boobs+ +part-clavicle+ +part-ear-left+ +part-ear-right+ +part-eye-left+ +part-eye-right+ +part-hair-top+ +part-hair-left+ +part-hair-right+ +part-hand-left+ +part-hand-right+ +part-mouth+ +part-tail+ +part-bell+ +part-exclamation-mark+ +part-exclamation-marks+ +part-heart+ +part-hearts+ +part-lantern+ +part-question-mark+ +part-question-marks+ +part-wool-ball+ ))

(print *part*)

(sb-ext:exit)
