.\"  cd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH cd 1 "23 Juli 2016" "cd(1)" "Meine eigenen Builtins"
.SH NAME
cd \-\- Andert das aktuell Ordner
.SH SYNOPSIS
cd [Option | Ordner]
.SH BESCHREIBUNG
Andert das aktuell Ordner.
.SH OPTIONEN
 ~  : Geht zu des Wertes das HOME Environmentvariable
    : Geht zu des Wertes das HOME Environmentvariable
 -  : Geht zu des Wertes das OLDPWD Environmentvariable (Letzte Ordner)
.SH BEISPIELE
 $> cd rust/
 $> cd ..
 $> cd ~
.SH AUTHOR
Jeremy Pepin (https://github.com/limaconoob)
